spring.config.import=optional:file:./.env[.properties]
spring.application.name=weatherapp

weather.api.key=${WEATHER_API_KEY}
weather.api.url=https://api.openweathermap.org/data/2.5/weather
weather.forecast.url=https://api.openweathermap.org/data/2.5/forecast
weather.geocode.url=https://api.openweathermap.org/geo/1.0/direct

weather.ai.api.url=${WEATHER_AI_API_URL:https://api.openai.com/v1/chat/completions}
weather.ai.api.key=${WEATHER_AI_API_KEY:}
weather.ai.model=${WEATHER_AI_MODEL:gpt-oss-20b}
weather.ai.temperature=0.3
weather.ai.max-tokens=500